# Generated by Django 5.2.5 on 2025-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_populate_author_fullname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("opened", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="full_name",
            field=models.CharField(blank=True, max_length=101),
        ),
    ]
