# Generated by Django 5.2.5 on 2025-08-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="number_of_pages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(blank=True, to="polls.tag"),
        ),
    ]
