# Generated by Django 5.2.5 on 2025-08-19 16:49

from django.db import migrations

# ================================================================
# ĐỊNH NGHĨA CÁC HÀM TRƯỚC
# ================================================================

# Hàm để chạy migration XUÔI: Kết hợp first_name và last_name thành full_name
def combine_names(apps, schema_editor):
    # Lấy model Author trong trạng thái hiện tại của migration
    Author = apps.get_model('polls', 'Author')
    for author in Author.objects.all():
        author.full_name = f"{author.first_name} {author.last_name}"
        author.save()

# Hàm để chạy migration NGƯỢC (hoàn tác): Xóa dữ liệu trong full_name
def uncombine_names(apps, schema_editor):
    Author = apps.get_model('polls', 'Author')
    for author in Author.objects.all():
        author.full_name = ""  # Xóa dữ liệu cũ đi
        author.save()

# ================================================================
# ĐỊNH NGHĨA CLASS MIGRATION SAU
# ================================================================

class Migration(migrations.Migration):

    dependencies = [
        # Phải trỏ đúng đến file migration 0002 trước đó
        ("polls", "0002_tag_author_email_alter_book_number_of_pages_and_more"),
    ]

    operations = [
        # Sử dụng các hàm đã được định nghĩa ở trên
        migrations.RunPython(combine_names, reverse_code=uncombine_names),
    ]